### ISSUE TITLE
[UI. Picker] 设置联动后，改变父选项时，后代选项尝试设置当前值为新的选项列表的默认值

### ISSUE THREAD

**Issue by lixinliang** [LEGO-SDK/LEGO-SDK-OC#4]
先设置时间为`10:30`
![image](https://user-images.githubusercontent.com/9375027/29449387-1ae3801e-842d-11e7-9d51-949e5ea0e77e.png)

改变日期为`19`号后，时间重置为`9:30`
![image](https://user-images.githubusercontent.com/9375027/29449444-649fcc94-842d-11e7-872c-16ecdc933e19.png)

**Comment by keyjacky** [comment]
fix
